# -*- coding: utf-8 -*-
"""Basketball AI Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_tBWoEEZN22A8_SS-j2XNJyJ1RUMEK_

# **Basketball AI Analyzer**

The project receives a link to a YouTube video that contains a segment of a basketball game and analyzes events between the players and the referees' decisions.
"""

# !git config --global user.email "yigaell@gmail.com"
# !git config --global user.name "Yigael Laloum"

# !pip install -U google-generativeai pytubefix

# PROMPT = """
# אתה מדריך שופטי כדורסל בכיר ומנתח ביצועים. תפקידך לנתח את סרטון הווידאו המצורף ולהפיק דוח שיפוט מקצועי בעברית.
# עליך להשתמש במידע ובתובנות מהקבצים המקצועיים שסופקו לך כדי לזהות אירועים.

# אנא נתח את האירועים הבאים:
# 1. **עבירות והפרות:** זהה עבירות אישיות, הפרות צעדים (Travel), חצי מגרש, וסיטואציות של AOS (זריקה לסל).
# 2. **אחריות שופטים (Primary/Secondary):** קבע מי היה צריך לשרוק - ה"פריימרי" (P) או ה"סקנדרי" (S), בהתאם למיקום (מוביל/Lead, סנטר/Center, עוקב/Trail).
# 3. **הערכת החלטה:** האם ההחלטה הייתה CC (שריקה נכונה), IC (שריקה שגויה), CNC (אי-שריקה נכונה) או INC (אי-שריקה שגויה).
# 4. **מכניקה ומיקום:** האם השופט ביצע 'Close Down' נכון? האם בוצעה רוטציה בזמן? האם הזווית מאפשרת לראות את המגע הלא חוקי?
# 5. **אירועים מיוחדים:** ניהול מאמנים, עבירות טכניות, עבירות בלתי ספורטיביות, התלהמות ספסל, וניהול סיכונים.
# 6. **עבודת צוות:** קשר עין בין שופטים, עזרה לפרטנר וסימונים כפולים מיותרים.

# **דגשים מקצועיים מתוך חומר הלימוד:**
# - זכור ש"מגע רך מאוד שלא משפיע על המשחק - נו קול (CNC) עדיף".
# - שים לב למיקום: "אל תהיה גבוה מדי, שמור על זוויות נכונות ביחס לשחקנים".
# - הימנע מסימונים מיותרים: "Less is more" - אין צורך לאשר סל שדה או להוסיף סימונים אם המוביל כבר סימן[cite: 19, 25, 26].
# - בצע סריקה של ה"צבע" (Paint) במקום לעקוב רק אחרי הכדור[cite: 5].

# **מבנה הפלט:**
# - רשום את זמן האירוע (Timestamp).
# - תיאור קצר של המהלך.
# - ניתוח מקצועי (החלטה, מכניקה ואחריות).

# התשובה חייבת להיות בעברית מקצועית בלבד.
# """

import os
import time
from google.colab import userdata
from pytubefix import YouTube
import google.generativeai as genai

# 1. חיבור ל-API
api_key = userdata.get('GOOGLE_API_KEY')
if not api_key:
    raise ValueError("API key לא נמצא!")

genai.configure(api_key=api_key)

def analyze_basketball_clip(video_url: str):
    try:
        video_url = video_url.strip()
        print("מוריד סרטון מיוטיוב...")
        yt = YouTube(video_url)
        stream = yt.streams.get_highest_resolution()  # או .filter(file_extension='mp4').first()
        path = stream.download(filename="game_clip.mp4")

        print("מעלה ל-Gemini...")
        uploaded_file = genai.upload_file(path=path, mime_type="video/mp4")

        # המתנה לעיבוד
        print("מעבד וידאו", end="")
        for _ in range(60):  # timeout ~5 דק'
            if uploaded_file.state.name == "ACTIVE":
                break
            if uploaded_file.state.name in ["FAILED", "ERROR"]:
                raise RuntimeError("העלאת הקובץ נכשלה")
            print(".", end="", flush=True)
            time.sleep(5)
            uploaded_file = genai.get_file(uploaded_file.name)
        else:
            raise TimeoutError("העלאת הקובץ לקח יותר מדי זמן")

        print("\nמנתח אירועים...")

        prompt = """
        נתח את סרטון הכדורסל המצורף בתור מדריך שופטי כדורסל FIBA.
        התייחס בפירוט ל:
        1. מיקומי שופטים ומכניקה (Lead/Center/Trail)
        2. Primary/Secondary אחריות
        3. הערכת החלטה (CC, CNC, IC, INC)
        4. דגשים מקצועיים
        ציין טיימסטאמפים מדויקים (MM:SS) לכל אירוע.
        השב בעברית מקצועית.
        """

        model = genai.GenerativeModel("models/gemini-2.5-flash")  # עדכני 2025
        response = model.generate_content([uploaded_file, prompt])

        print("\n--- דוח ניתוח משחק ---")
        print(response.text)

    except Exception as e:
        print(f"\nשגיאה: {str(e)}")
    finally:
        if os.path.exists(path):
            os.remove(path)
        # אפשר גם למחוק את הקובץ מה-API אם רוצים
        # genai.delete_file(uploaded_file.name)

# הרצה
url = "https://www.youtube.com/watch?v=5IWClBjtHb8"
analyze_basketball_clip(url)



